// ═══════════════════════════════════════════════════════════════════════
// ═══════════════════════════════════════════════════════════════════════
//
//                                      op:"detect", entry:"main" }
//    {
//      "ok": true,
//      "platform": "windows",
//        ...
//      ],
//    }
//
//            env.set / whoami() / log() / __platform()
//                  ipconfig / wmic / tasklist
// ═══════════════════════════════════════════════════════════════════════

var AV_MAP = {
    "360tray.exe": "360安全卫士",
    "360safe.exe": "360安全卫士",
    "zhudongfangyu.exe": "360安全卫士",
    "360rp.exe": "360杀毒",
    "360sd.exe": "360杀毒",
    "360safebox.exe": "360杀毒",
    "safeboxtray.exe": "360杀毒",
    "scrscan.exe": "360杀毒",
    "ksafe.exe": "金山卫士",
    "ksafetray.exe": "金山毒霸",
    "ksafesvc.exe": "金山毒霸",
    "kwatch.exe": "金山毒霸",
    "kxetray.exe": "金山毒霸",
    "kmailmon.exe": "金山毒霸",
    "knsdtray.exe": "可牛杀毒",
    "kswebshield.exe": "金山网盾",
    "kpfwtray.exe": "金山网镖",
    "hipstray.exe": "火绒安全",
    "wsctrl.exe": "火绒安全",
    "usysdiag.exe": "火绒安全",
    "qqpcrtp.exe": "QQ电脑管家",
    "qqpctray.exe": "QQ电脑管家",
    "ravmond.exe": "瑞星杀毒",
    "rfwmain.exe": "瑞星防火墙",
    "kvmonxp.exe": "江民杀毒",
    "safedog.exe": "安全狗",
    "safedogguardcenter.exe": "安全狗",
    "safedogupdatecenter.exe": "安全狗",
    "safedogsiteiis.exe": "安全狗",
    "safedogtray.exe": "安全狗",
    "safedogserverui.exe": "安全狗",
    "d_safe_manage.exe": "D盾",
    "d_manage.exe": "D盾",
    "yunsuo_agent_service.exe": "云锁",
    "yunsuo_agent_daemon.exe": "云锁",
    "gov_defence_service.exe": "云锁",
    "gov_defence_daemon.exe": "云锁",
    "hwspanel.exe": "护卫神",
    "hws_ui.exe": "护卫神",
    "hws.exe": "护卫神",
    "hwsd.exe": "护卫神",
    "parmor.exe": "木马克星",
    "iparmor.exe": "木马克星",
    "beikesan.exe": "贝壳云安全",
    "trojanhunter.exe": "木马猎手",
    "gg.exe": "巨盾网游安全盾",
    "adam.exe": "绿鹰安全精灵",
    "ast.exe": "超级巡警",
    "ananwidget.exe": "墨者安全专家",
    "mpmon.exe": "微点主动防御",
    "baidusdsvc.exe": "百度杀毒",
    "baidusdtray.exe": "百度杀毒",
    "baidusd.exe": "百度杀毒",
    "bddownloader.exe": "百度卫士",
    "baiduansvx.exe": "百度卫士",
    "agb.exe": "安天防线",
    "ahprocmonserver.exe": "安天防线",
    "fyfirewall.exe": "风云防火墙",
    "pfw.exe": "天网防火墙",
    "emet.exe": "EMET(微软加固)",
    "emet_agent.exe": "EMET(微软加固)",
    "emet_service.exe": "EMET(微软加固)",
    "msmpeng.exe": "Windows Defender",
    "mssecess.exe": "Microsoft Security Essentials",
    "avp.exe": "Kaspersky(卡巴斯基)",
    "avp32.exe": "Kaspersky(卡巴斯基)",
    "avpcc.exe": "Kaspersky(卡巴斯基)",
    "avpm.exe": "Kaspersky(卡巴斯基)",
    "kav.exe": "Kaspersky(卡巴斯基)",
    "kavmm.exe": "Kaspersky(卡巴斯基)",
    "kavpf.exe": "Kaspersky(卡巴斯基)",
    "kavpfw.exe": "Kaspersky(卡巴斯基)",
    "kavstart.exe": "Kaspersky(卡巴斯基)",
    "kavsvc.exe": "Kaspersky(卡巴斯基)",
    "kavsvcui.exe": "Kaspersky(卡巴斯基)",
    "ccsvchst.exe": "Norton(诺顿)",
    "ccapp.exe": "Norton(诺顿)",
    "ccsetmgr.exe": "Norton(诺顿)",
    "ccregvfy.exe": "Norton(诺顿)",
    "rtvscan.exe": "Norton(诺顿)",
    "npfmntor.exe": "Norton(诺顿)",
    "navapsvc.exe": "Norton(诺顿)",
    "navapw32.exe": "Norton(诺顿)",
    "navw32.exe": "Norton(诺顿)",
    "mcshield.exe": "McAfee",
    "tbmon.exe": "McAfee",
    "frameworkservice.exe": "McAfee",
    "cmdagent.exe": "McAfee",
    "mctray.exe": "McAfee",
    "mcagent.exe": "McAfee",
    "mcupdate.exe": "McAfee",
    "mcvsshld.exe": "McAfee",
    "mcvsrte.exe": "McAfee",
    "egui.exe": "ESET NOD32",
    "ekrn.exe": "ESET NOD32",
    "eguiproxy.exe": "ESET NOD32",
    "nod32.exe": "ESET NOD32",
    "ashdisp.exe": "Avast(爱维士)",
    "avastui.exe": "Avast(爱维士)",
    "aswupdsv.exe": "Avast(爱维士)",
    "aswscan.exe": "Avast(爱维士)",
    "ashserv.exe": "Avast(爱维士)",
    "ashmaisv.exe": "Avast(爱维士)",
    "ashwebsv.exe": "Avast(爱维士)",
    "avcenter.exe": "Avira(小红伞)",
    "avguard.exe": "Avira(小红伞)",
    "avgnt.exe": "Avira(小红伞)",
    "sched.exe": "Avira(小红伞)",
    "vsserv.exe": "BitDefender(比特梵德)",
    "vsservppl.exe": "BitDefender(比特梵德)",
    "bdagent.exe": "BitDefender(比特梵德)",
    "bdswitch.exe": "BitDefender(比特梵德)",
    "xcommsvr.exe": "BitDefender(比特梵德)",
    "avgwdsvc.exe": "AVG杀毒",
    "avgcc32.exe": "AVG杀毒",
    "avgctrl.exe": "AVG杀毒",
    "avgemc.exe": "AVG杀毒",
    "avgsrv.exe": "AVG杀毒",
    "avgserv.exe": "AVG杀毒",
    "avgserv9.exe": "AVG杀毒",
    "avgw.exe": "AVG杀毒",
    "avg.exe": "AVG杀毒",
    "avgchsvx.exe": "AVG杀毒",
    "avgntflt.exe": "AVG杀毒",
    "avgtray.exe": "AVG杀毒",
    "avgupsvc.exe": "AVG杀毒",
    "avgfwsrv.exe": "AVG杀毒",
    "spidernt.exe": "Dr.Web",
    "drweb.exe": "Dr.Web",
    "drwadins.exe": "Dr.Web",
    "spidercpl.exe": "Dr.Web",
    "spiderml.exe": "Dr.Web",
    "spiderui.exe": "Dr.Web",
    "cureit.exe": "Dr.Web",
    "savmain.exe": "Sophos杀毒",
    "savprogress.exe": "Sophos杀毒",
    "sophosui.exe": "Sophos杀毒",
    "sophosfs.exe": "Sophos杀毒",
    "sophoshealth.exe": "Sophos杀毒",
    "sophossafestore64.exe": "Sophos杀毒",
    "sophoscleanm.exe": "Sophos杀毒",
    "swnetsup.exe": "Sophos杀毒",
    "f-prot.exe": "F-Prot AntiVirus",
    "fprot.exe": "F-Prot AntiVirus",
    "fprotray.exe": "F-Prot AntiVirus",
    "f-secure.exe": "F-Secure",
    "fsavgui.exe": "F-Secure",
    "fameh32.exe": "F-Secure",
    "fch32.exe": "F-Secure",
    "fih32.exe": "F-Secure",
    "findviru.exe": "F-Secure",
    "fnrb32.exe": "F-Secure",
    "fsaa.exe": "F-Secure",
    "fsav.exe": "F-Secure",
    "fsav32.exe": "F-Secure",
    "fsgk32.exe": "F-Secure",
    "fsm32.exe": "F-Secure",
    "fsma32.exe": "F-Secure",
    "fsmb32.exe": "F-Secure",
    "fssm32.exe": "F-Secure",
    "fsbwsys.exe": "F-Secure",
    "fsdfwd.exe": "F-Secure",
    "tmbmsrv.exe": "趋势科技",
    "ntrtscan.exe": "趋势科技",
    "pcscan.exe": "趋势科技",
    "ofcpfwsvc.exe": "趋势科技",
    "tmlisten.exe": "趋势科技",
    "tmnetsrv.exe": "趋势科技",
    "tmpfw.exe": "趋势科技",
    "tmproxy.exe": "趋势科技",
    "patch.exe": "趋势科技",
    "remupd.exe": "Panda(熊猫卫士)",
    "pavfires.exe": "Panda(熊猫卫士)",
    "pavfnsvr.exe": "Panda(熊猫卫士)",
    "pavkre.exe": "Panda(熊猫卫士)",
    "pavprot.exe": "Panda(熊猫卫士)",
    "pavproxy.exe": "Panda(熊猫卫士)",
    "pavprsrv.exe": "Panda(熊猫卫士)",
    "pavsrv51.exe": "Panda(熊猫卫士)",
    "pavss.exe": "Panda(熊猫卫士)",
    "prevsvr.exe": "Panda(熊猫卫士)",
    "fortitray.exe": "飞塔(Fortinet)",
    "vsmon.exe": "ZoneAlarm",
    "zapro.exe": "ZoneAlarm",
    "zonealarm.exe": "ZoneAlarm",
    "cpf.exe": "Comodo(科摩多)",
    "cfp.exe": "Comodo(科摩多)",
    "outpost.exe": "Outpost防火墙",
    "sphinx.exe": "SPHINX防火墙",
    "a2service.exe": "Emsisoft Anti-Malware",
    "a2guard.exe": "Emsisoft Anti-Malware",
    "a2cmd.exe": "Emsisoft Anti-Malware",
    "a2free.exe": "Emsisoft Anti-Malware",
    "vba32lder.exe": "VBA32杀毒",
    "mongoosagui.exe": "Mongoosa杀毒",
    "coranticontrolcenter32.exe": "Coranti杀毒",
    "cmctrayicon.exe": "CMC杀毒",
    "k7tsecurity.exe": "K7杀毒",
    "unthreat.exe": "UnThreat杀毒",
    "cksoftshiedantivirus4.exe": "Shield杀毒",
    "avwatchservice.exe": "VIRUSfighter杀毒",
    "arcatasksservice.exe": "ArcaVir杀毒",
    "iptray.exe": "Immunet杀毒",
    "psafesystray.exe": "PSafe杀毒",
    "nspupsvc.exe": "nProtect杀毒",
    "spywareterminatorshield.exe": "SpywareTerminator",
    "bkavservice.exe": "Bkav杀毒",
    "sbamsvc.exe": "VIPRE",
    "quhlpsvc.exe": "QUICK HEAL杀毒",
    "qhactivedefense.exe": "QUICK HEAL杀毒",
    "mbamservice.exe": "Malwarebytes",
    "mbamtray.exe": "Malwarebytes",
    "mbam.exe": "Malwarebytes",
    "wrsa.exe": "Webroot杀毒",
    "wrsvc.exe": "Webroot杀毒",
    "webroot.exe": "Webroot杀毒",
    "escansvc.exe": "eScan杀毒",
    "escantray.exe": "eScan杀毒",
    "cleaner8.exe": "The Cleaner杀毒",
    "avk.exe": "AntiVirusKit",
    "avz.exe": "AVZ杀软",
    "fweng.exe": "McAfee",
    "fwinst.exe": "McAfee",
    "fwmgr.exe": "McAfee",
    "fwrules.exe": "McAfee",
    "fwstub.exe": "McAfee",
    "fwtrw.exe": "McAfee",
    "mcafeefire.exe": "McAfee",
    "engineserver.exe": "McAfee",
    "mfeann.exe": "McAfee",
    "mcscript.exe": "McAfee",
    "updaterui.exe": "McAfee",
    "udaterui.exe": "McAfee",
    "naprdmgr.exe": "McAfee",
    "cleanup.exe": "McAfee",
    "frminst.exe": "McAfee",
    "mcscript_inuse.exe": "McAfee",
    "shstat.exe": "McAfee",
    "vstskmgr.exe": "McAfee",
    "scan32.exe": "McAfee",
    "hipsvc.exe": "McAfee",
    "firetray.exe": "McAfee",
    "firesvc.exe": "McAfee",
    "mcmnhdlr.exe": "McAfee",
    "mctool.exe": "McAfee",
    "mgavrtcl.exe": "McAfee",
    "mgavrte.exe": "McAfee",
    "mpfagent.exe": "McAfee",
    "mpfservice.exe": "McAfee",
    "mpftray.exe": "McAfee",
    "vshwin32.exe": "McAfee",
    "vsmain.exe": "McAfee",
    "vsstat.exe": "McAfee",
    "avira.exe": "Avira(小红伞)",
    "avesvc.exe": "Avira(小红伞)",
    "avsched32.exe": "Avira(小红伞)",
    "avwupsrv.exe": "Avira(小红伞)",
    "aupdate.exe": "Symantec",
    "avgntmgr.exe": "AVG杀毒",
    "avgnsx.exe": "AVG杀毒",
    "avgcsrvx.exe": "AVG杀毒",
    "avgam.exe": "AVG杀毒",
    "avgcc.exe": "AVG杀毒",
    "avinitnt.exe": "Command AntiVirus",
    "blackd.exe": "BlackICE",
    "blackice.exe": "BlackICE",
    "rapapp.exe": "BlackICE",
    "defwatch.exe": "Norton(诺顿)",
    "ewidoctrl.exe": "Ewido Security Suite",
    "guard.exe": "ewido",
    "guarddog.exe": "ewido",
    "freshclam.exe": "ClamAV",
    "clamwin.exe": "ClamWin",
    "inocit.exe": "eTrust",
    "inorpc.exe": "eTrust",
    "inort.exe": "eTrust",
    "inotask.exe": "eTrust",
    "inouptng.exe": "eTrust",
    "isafe.exe": "eTrust",
    "vettray.exe": "eTrust",
    "spbbcsvc.exe": "Symantec",
    "symproxysvc.exe": "Symantec",
    "symsport.exe": "Symantec",
    "symwsc.exe": "Symantec",
    "symtray.exe": "Symantec",
    "nisserv.exe": "Norton(诺顿)",
    "nisum.exe": "Norton(诺顿)",
    "nmain.exe": "Norton(诺顿)",
    "nprotect.exe": "Norton(诺顿)",
    "nsmdtr.exe": "Norton(诺顿)",
    "qconsole.exe": "Norton(诺顿)",
    "qserver.exe": "Norton(诺顿)",
    "luall.exe": "Norton(诺顿)",
    "luau.exe": "Norton(诺顿)",
    "lucomserver.exe": "Norton(诺顿)",
    "pestpatrol.exe": "Ikarus",
    "guardnt.exe": "IKARUS",
    "pctav.exe": "PC Tools AntiVirus",
    "spybotsd.exe": "Spybot Search & Destroy",
    "swagent.exe": "SonicWALL",
    "swdoctor.exe": "SonicWALL",
    "sdhelp.exe": "Spyware Doctor",
    "vcrmon.exe": "VirusChaser",
    "vrmonnt.exe": "HAURI",
    "vrmonsvc.exe": "HAURI",
    "tnbutil.exe": "趋势科技",
    "pop3trap.exe": "趋势科技",
    "pccguide.exe": "趋势科技",
    "pcciomon.exe": "趋势科技",
    "pccntmon.exe": "趋势科技",
    "pccpfw.exe": "趋势科技",
    "pcctlcom.exe": "趋势科技",
    "alertsvc.exe": "Norton(诺顿)",
    "navlu32.exe": "Norton(诺顿)",
    "nav.exe": "Norton(诺顿)",
    "onlinent.exe": "趋势科技",
    "op_mon.exe": "Outpost防火墙",
    "persfw.exe": "Tiny Personal Firewall",
    "amon.exe": "Tiny Personal Firewall",
    "rtvscn95.exe": "趋势科技",
    "savadminservice.exe": "Sophos杀毒",
    "savscan.exe": "Sophos杀毒",
    "symlcsvc.exe": "Symantec",
    "synmgr.exe": "Symantec",
    "tmntsrv.exe": "趋势科技",
    "minilog.exe": "ZoneAlarm",
};

function main(args) {
    var op = args.op || "detect";
    if (op !== "detect") {
        return { "ok": false, "error": "unknown op: " + op };
    }

    var platform = __platform();
    var procs = proc.list();
    var total = procs.length;

    var matched = [];   // { name, product, pid }
    var unmatched = [];

    for (var i = 0; i < procs.length; i++) {
        var p = procs[i];
        var name = p.name || "";
        var key = name.toLowerCase();
        var product = AV_MAP[key];

        if (product !== undefined) {
            matched.push({ "name": name, "product": product, "pid": p.pid });
        } else if (name) {
            unmatched.push(name);
        }
    }

    var byProduct = {};
    var order = [];
    for (var j = 0; j < matched.length; j++) {
        var item = matched[j];
        var prod = item.product;
        if (byProduct[prod] === undefined) {
            byProduct[prod] = { "product": prod, "processes": [] };
            order.push(prod);
        }
        byProduct[prod].processes.push({ "name": item.name, "pid": item.pid });
    }

    var av = [];
    for (var k = 0; k < order.length; k++) {
        av.push(byProduct[order[k]]);
    }

    return {
        "ok": true,
        "platform": platform,
        "total_processes": total,
        "av": av,
        "unmatched": unmatched
    };
}
